//buscar produtos
GET http://localhost:5005/produtos

###
POST http://localhost:5005/produtos
Content-Type: application/json

{
    "id": 234,
    "nome": "Produto 2",
    "Preco": 345,
    "off": 17
}

###

//buscar produto por id
GET http://localhost:5005/produtos/123